[package]
name = "anomalog-rust"
version = "0.1.0"
edition = "2024"

[lib]
name = "_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
logmole-core = { git = "https://github.com/krtffl/logmole", rev = "ea7ac378a5b31803dd9174edaa3bdf136e3e59c5" }
serde_json = "1"
